"""add_chat_messages_role_created_at_index

Revision ID: 011
Revises: 010
Create Date: 2026-04-17 15:00:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "011"
down_revision = "010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_chat_messages_role_created_at", "chat_messages", ["role", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_messages_role_created_at", table_name="chat_messages")
    # ### end Alembic commands ###
