"""add_chat_messages_role_created_at_index

Revision ID: 011_add_chat_messages_role_created_at_index
Revises: 010_add_admin_query_reviews
Create Date: 2026-04-17 15:00:00.000000

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '011_add_chat_messages_role_created_at_index'
down_revision = '010_add_admin_query_reviews'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_messages_role_created_at', 'chat_messages', ['role', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_role_created_at', table_name='chat_messages')
    # ### end Alembic commands ###